server:
  port: 8080

spring:
  application:
    name: Bebka-Spring

  datasource:
    url: jdbc:postgresql://localhost:5432/bebka_spring
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


spring:
  profiles:
    active: dev

logging:
  level:
    root: INFO
    com.helin.springboot: DEBUG
    org.hibernate.SQL: WARN
